import type { CiProvider, Config } from '../config/schema.ts';
import { platformsFor } from '../secrets.ts';

export interface SecretRequirement {
  name: string;
  description: string;
}

/**
 * Names and descriptions here MUST match exactly what the generated
 * Fastfile / Appfile / CI workflow templates read (`ENV["..."]` /
 * `secrets.NAME`) — grep `src/templates/**` before adding an entry.
 * `github-releases` is intentionally absent from both tables: nothing
 * currently rendered reads a secret for it.
 */
const FIREBASE_SERVICE_ACCOUNT: SecretRequirement = {
  name: 'FIREBASE_SERVICE_ACCOUNT_JSON',
  description:
    'Firebase service account JSON (full file contents) with App Distribution admin access. Firebase console → Project settings → Service accounts → Generate new private key.',
};

const ANDROID_TARGET_SECRETS: Record<string, SecretRequirement[]> = {
  firebase: [
    {
      name: 'FIREBASE_APP_ID_ANDROID',
      description:
        'Firebase App Distribution app id for the Android app. Firebase console → Project settings → General → Your apps.',
    },
    FIREBASE_SERVICE_ACCOUNT,
  ],
  testflight: [],
  'github-releases': [],
  store: [
    {
      name: 'PLAY_STORE_JSON_KEY',
      description:
        'Google Play service account JSON key with Release Manager access. Play Console → Setup → API access → Service accounts.',
    },
  ],
};

const IOS_TARGET_SECRETS: Record<string, SecretRequirement[]> = {
  firebase: [
    {
      name: 'FIREBASE_APP_ID_IOS',
      description:
        'Firebase App Distribution app id for the iOS app. Firebase console → Project settings → General → Your apps.',
    },
    FIREBASE_SERVICE_ACCOUNT,
  ],
  testflight: [
    {
      name: 'APP_STORE_CONNECT_API_KEY_PATH',
      description:
        'Path to the App Store Connect API key file fastlane uses to upload builds. App Store Connect → Users and Access → Integrations → App Store Connect API.',
    },
  ],
  'github-releases': [],
  store: [
    {
      name: 'APP_STORE_CONNECT_API_KEY_PATH',
      description:
        'Path to the App Store Connect API key file fastlane uses to upload builds. App Store Connect → Users and Access → Integrations → App Store Connect API.',
    },
  ],
};

/**
 * Every iOS lane calls `match(...)` unconditionally (guarded only by
 * `ENV["MATCH_PASSWORD"]` at runtime, not by distribution target) — so any
 * iOS build profile, regardless of its distribution, needs these to sign.
 */
const IOS_SIGNING_SECRETS: SecretRequirement[] = [
  {
    name: 'MATCH_PASSWORD',
    description:
      'Passphrase that decrypts the fastlane match certificates repo. Choose one when running `fastlane match init`.',
  },
  {
    name: 'MATCH_GIT_BASIC_AUTHORIZATION',
    description:
      'Base64-encoded `username:token` with read access to the match certificates repo, e.g. `echo -n "user:token" | base64`.',
  },
];

const OTA_SECRET: SecretRequirement = {
  name: 'OTA_UPLOAD_KEY',
  description:
    'Shared upload key the OTA server accepts on `/api/upload`. Set the same value on the OTA server and here.',
};

/** Derives the CI secrets required by what `generate` actually renders for this config. */
export function deriveRequiredSecrets(config: Config): SecretRequirement[] {
  const required = new Map<string, SecretRequirement>();

  for (const profile of Object.values(config.build)) {
    const targets = profile.distribution.split('+').map((t) => t.trim());
    for (const platform of platformsFor(profile.platform)) {
      const table = platform === 'android' ? ANDROID_TARGET_SECRETS : IOS_TARGET_SECRETS;
      for (const target of targets) {
        for (const req of table[target] ?? []) required.set(req.name, req);
      }
      if (platform === 'ios') {
        for (const req of IOS_SIGNING_SECRETS) required.set(req.name, req);
      }
    }
    if (profile.ota) required.set(OTA_SECRET.name, OTA_SECRET);
  }

  return [...required.values()].sort((a, b) => a.name.localeCompare(b.name));
}

export function secretSetCommand(ci: CiProvider, name: string): string {
  return ci === 'gitlab' ? `glab variable set ${name}` : `gh secret set ${name}`;
}

export function buildSetupMarkdown(secrets: SecretRequirement[], ci: CiProvider): string {
  const lines: string[] = [
    '# CI secrets setup',
    '',
    'Auto-generated by `rn-workflows generate`. Regenerate with `npx rn-workflows generate`.',
    '',
    'These are the CI secrets the generated Fastlane and CI files read at build time.',
    '`rn-workflows setup` can collect and upload most of these for you.',
    '',
  ];

  for (const req of secrets) {
    lines.push(`## ${req.name}`, '', req.description, '', '```sh', `${secretSetCommand(ci, req.name)} "<value>"`, '```', '');
  }

  return lines.join('\n');
}
